use Port_project;
rename table mytable to customer;
ALTER TABLE mytable RENAME TO customer;


-- Q1. what is the total revenue generated by male vs. female customer?
select gender, sum(purchase_amount) as revenue from customer
group by gender;

-- Q2. Which customer use a discount but still spent more than the avg purchase amount
select customer_id, purchase_amount from customer
where purchase_amount>=(select avg(purchase_amount) from customer);


-- Q3. which are the top 5 products with the highest avg review rating?
select item_purchased, round(avg(review_rating),2) as review_rating from customer 
group by item_purchased order by review_rating desc  limit 5;

-- Q4. compare the avg purchase amounts btw Standard and Express shipping.
select shipping_type, 
Round(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribed customers spend more? compare avg spend and total revenue
-- btw subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    Round(SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/ COUNT(*)*100,2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customer into New, returning, and loyal based on their total
-- number of previous purchases, and show the count of each segemnt.
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
Select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Arre customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;